# Generated by Django 4.2.2 on 2023-10-08 17:32

from django.db import migrations, models
import robots.models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[robots.models.validate_model_length]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=5, validators=[robots.models.validate_serial_length, robots.models.validate_serial_regex]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, validators=[robots.models.validate_version_length]),
        ),
    ]
